name: CI

# Controls when the workflow will run
# Triggers the workflow on push or pull request events on all branches
on: [push, pull_request]

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies
      run: |
        cd angular-psd
        npm install

    - name: Build frontend
      run: |
        cd angular-psd
        npm run build

  backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '21'

    - name: Build backend
      run: |
        cd backend
        ./mvnw clean install

    - name: Run backend tests
      run: |
        cd backend
        ./mvnw test

# Add more steps as needed for additional checks, tests, or tasks
